package EquationCorba;


/**
* EquationCorba/EquationInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Equation.idl
* vendredi 25 décembre 2020 16 h 11 WEST
*/

public abstract class EquationInterfacePOA extends org.omg.PortableServer.Servant
 implements EquationCorba.EquationInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("equation", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EquationCorba/EquationInterface/equation
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double c = in.read_double ();
         String $result = null;
         $result = this.equation (a, b, c);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EquationCorba/EquationInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EquationInterface _this() 
  {
    return EquationInterfaceHelper.narrow(
    super._this_object());
  }

  public EquationInterface _this(org.omg.CORBA.ORB orb) 
  {
    return EquationInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class EquationInterfacePOA
