package EquationCorba;


/**
* EquationCorba/EquationInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Equation.idl
* vendredi 25 décembre 2020 16 h 11 WEST
*/

public interface EquationInterface extends EquationInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EquationInterface
