package EquationCorba;

/**
* EquationCorba/EquationInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Equation.idl
* vendredi 25 décembre 2020 16 h 11 WEST
*/

public final class EquationInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public EquationCorba.EquationInterface value = null;

  public EquationInterfaceHolder ()
  {
  }

  public EquationInterfaceHolder (EquationCorba.EquationInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EquationCorba.EquationInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EquationCorba.EquationInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EquationCorba.EquationInterfaceHelper.type ();
  }

}
