package EquationCorba;


/**
* EquationCorba/EquationInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Equation.idl
* vendredi 25 décembre 2020 16 h 11 WEST
*/

public interface EquationInterfaceOperations 
{
  String equation (double a, double b, double c);
} // interface EquationInterfaceOperations
